//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;
using System.Xml.Serialization;
using SMSBnRTools.classes;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class smses {
    
    private object[] itemsField;
    
    private ushort countField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("mms", typeof(smsesMms))]
    [System.Xml.Serialization.XmlElementAttribute("sms", typeof(smsesSms))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class smsesMms : IMobileMessage {
    
    private smsesMmsPart[] partsField;
    
    private byte text_onlyField;
    
    private bool text_onlyFieldSpecified;
    
    private string subField;
    
    private string retr_stField;
    
    private ulong dateField;
    
    private string ct_clsField;
    
    private string sub_csField;
    
    private byte readField;
    
    private string ct_lField;
    
    private string tr_idField;
    
    private string stField;
    
    private byte msg_boxField;
    
    private string addressField;
    
    private string m_clsField;
    
    private string d_tmField;
    
    private string read_statusField;
    
    private string ct_tField;
    
    private string retr_txt_csField;
    
    private byte d_rptField;
    
    private string m_idField;
    
    private byte date_sentField;
    
    private byte seenField;
    
    private byte m_typeField;
    
    private string vField;
    
    private string expField;
    
    private byte priField;
    
    private byte rrField;
    
    private string resp_txtField;
    
    private string rpt_aField;
    
    private byte lockedField;
    
    private string retr_txtField;
    
    private string resp_stField;
    
    private string m_sizeField;
    
    private string readable_dateField;
    
    private string contact_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("part", IsNullable=false)]
    public smsesMmsPart[] parts {
        get {
            return this.partsField;
        }
        set {
            this.partsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte text_only {
        get {
            return this.text_onlyField;
        }
        set {
            this.text_onlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool text_onlySpecified {
        get {
            return this.text_onlyFieldSpecified;
        }
        set {
            this.text_onlyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sub {
        get {
            return this.subField;
        }
        set {
            this.subField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retr_st {
        get {
            return this.retr_stField;
        }
        set {
            this.retr_stField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override ulong date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ct_cls {
        get {
            return this.ct_clsField;
        }
        set {
            this.ct_clsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sub_cs {
        get {
            return this.sub_csField;
        }
        set {
            this.sub_csField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte read {
        get {
            return this.readField;
        }
        set {
            this.readField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ct_l {
        get {
            return this.ct_lField;
        }
        set {
            this.ct_lField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tr_id {
        get {
            return this.tr_idField;
        }
        set {
            this.tr_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string st {
        get {
            return this.stField;
        }
        set {
            this.stField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte msg_box {
        get {
            return this.msg_boxField;
        }
        set {
            this.msg_boxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string m_cls {
        get {
            return this.m_clsField;
        }
        set {
            this.m_clsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string d_tm {
        get {
            return this.d_tmField;
        }
        set {
            this.d_tmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string read_status {
        get {
            return this.read_statusField;
        }
        set {
            this.read_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ct_t {
        get {
            return this.ct_tField;
        }
        set {
            this.ct_tField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retr_txt_cs {
        get {
            return this.retr_txt_csField;
        }
        set {
            this.retr_txt_csField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte d_rpt {
        get {
            return this.d_rptField;
        }
        set {
            this.d_rptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string m_id {
        get {
            return this.m_idField;
        }
        set {
            this.m_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte date_sent {
        get {
            return this.date_sentField;
        }
        set {
            this.date_sentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte seen {
        get {
            return this.seenField;
        }
        set {
            this.seenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte m_type {
        get {
            return this.m_typeField;
        }
        set {
            this.m_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string v {
        get {
            return this.vField;
        }
        set {
            this.vField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string exp {
        get {
            return this.expField;
        }
        set {
            this.expField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte pri {
        get {
            return this.priField;
        }
        set {
            this.priField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte rr {
        get {
            return this.rrField;
        }
        set {
            this.rrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resp_txt {
        get {
            return this.resp_txtField;
        }
        set {
            this.resp_txtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rpt_a {
        get {
            return this.rpt_aField;
        }
        set {
            this.rpt_aField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte locked {
        get {
            return this.lockedField;
        }
        set {
            this.lockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string retr_txt {
        get {
            return this.retr_txtField;
        }
        set {
            this.retr_txtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string resp_st {
        get {
            return this.resp_stField;
        }
        set {
            this.resp_stField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string m_size {
        get {
            return this.m_sizeField;
        }
        set {
            this.m_sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override string readable_date {
        get {
            return this.readable_dateField;
        }
        set {
            this.readable_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override string contact_name {
        get {
            return this.contact_nameField;
        }
        set {
            this.contact_nameField = value;
        }
    }

    public override string bodyText => this.parts.FirstOrDefault(x => x.ct == "text/plain")?.text ?? string.Empty;

    public override byte sentReceived => this.msg_box;
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class smsesMmsPart {
    
    private sbyte seqField;
    
    private string ctField;
    
    private string nameField;
    
    private string chsetField;
    
    private string cdField;
    
    private string fnField;
    
    private string cidField;
    
    private string clField;
    
    private string ctt_sField;
    
    private string ctt_tField;
    
    private string textField;
    
    private string dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte seq {
        get {
            return this.seqField;
        }
        set {
            this.seqField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ct {
        get {
            return this.ctField;
        }
        set {
            this.ctField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chset {
        get {
            return this.chsetField;
        }
        set {
            this.chsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cd {
        get {
            return this.cdField;
        }
        set {
            this.cdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fn {
        get {
            return this.fnField;
        }
        set {
            this.fnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cid {
        get {
            return this.cidField;
        }
        set {
            this.cidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cl {
        get {
            return this.clField;
        }
        set {
            this.clField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ctt_s {
        get {
            return this.ctt_sField;
        }
        set {
            this.ctt_sField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ctt_t {
        get {
            return this.ctt_tField;
        }
        set {
            this.ctt_tField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class smsesSms : IMobileMessage{
    
    private byte protocolField;
    
    private bool protocolFieldSpecified;
    
    private string addressField;
    
    private ulong dateField;
    
    private byte typeField;
    
    private string subjectField;
    
    private string bodyField;
    
    private string toaField;
    
    private string sc_toaField;
    
    private string service_centerField;
    
    private byte readField;
    
    private sbyte statusField;
    
    private byte lockedField;
    
    private bool lockedFieldSpecified;
    
    private ulong date_sentField;
    
    private bool date_sentFieldSpecified;
    
    private string readable_dateField;
    
    private string contact_nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte protocol {
        get {
            return this.protocolField;
        }
        set {
            this.protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool protocolSpecified {
        get {
            return this.protocolFieldSpecified;
        }
        set {
            this.protocolFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override string address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override ulong date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string toa {
        get {
            return this.toaField;
        }
        set {
            this.toaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sc_toa {
        get {
            return this.sc_toaField;
        }
        set {
            this.sc_toaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string service_center {
        get {
            return this.service_centerField;
        }
        set {
            this.service_centerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte read {
        get {
            return this.readField;
        }
        set {
            this.readField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte locked {
        get {
            return this.lockedField;
        }
        set {
            this.lockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lockedSpecified {
        get {
            return this.lockedFieldSpecified;
        }
        set {
            this.lockedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong date_sent {
        get {
            return this.date_sentField;
        }
        set {
            this.date_sentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool date_sentSpecified {
        get {
            return this.date_sentFieldSpecified;
        }
        set {
            this.date_sentFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override string readable_date {
        get {
            return this.readable_dateField;
        }
        set {
            this.readable_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public override string contact_name {
        get {
            return this.contact_nameField;
        }
        set {
            this.contact_nameField = value;
        }
    }

    public override string bodyText => this.bodyField;
    public override byte sentReceived => this.type;
}
